version: "3.8"
services:
  react:
    build:
      context: ./
      dockerfile: docker/dockerfile
      target: dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: ${APP_MODE}
      APP_THEME: ${APP_THEME}