# Use Node.js as the base image
FROM node:18-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to install dependencies
COPY package.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY ./src .

# Build the React app for production
# RUN npm run dev

# Use a lightweight web server to serve the production build
FROM nginx:alpine

# Copy the React build to the nginx HTML directory
COPY --from=0 /app/build /usr/share/nginx/html

# Expose the default nginx port
EXPOSE 80

# Start nginx when the container launches
CMD ["nginx", "-g", "daemon off;"]